# NameOfTheBenchmark:
#   - name: 'name of the exec' [Mandatory]
#     num_exec: 1 (number of execution) [Mandatory]
#     size: 512 (global size)
#     local_size: 32 (local size)
#     num_iters: 1 (number of iterations)
#     num_runs: 5 (number of runs in the instance)
#     device: gpu (or cpu)
### You can add more than one instance by adding a new -name and description in the same benchmark
### Then it is possible to add more benchmarks

HostDeviceBandwidth:
  - name: 'host_device_bandwidth'
    num_exec: 1
    size: 512
    local_size: 32
    device: 'gpu'
    num_runs: 20